// apps/client/src/routes/(logged-in)/(library)/releases/+page.svelte
<script lang="ts">
  import { makeImageUrl } from 'mutils'

  import CommaList from '$lib/atoms/CommaList.svelte'
  import FlowGrid from '$lib/atoms/FlowGrid.svelte'
  import CoverArt from '$lib/components/CoverArt.svelte'
  import FullscreenLoader from '$lib/components/FullscreenLoader.svelte'
  import { getContextClient } from '$lib/trpc'

  const trpc = getContextClient()
  const releasesQuery = trpc.releases.getAll.query({})
</script>

{#if $releasesQuery.data}
  <FlowGrid>
    {#each $releasesQuery.data as release (release.id)}
      <div class="w-full">
        <a href="/releases/{release.id}" class="w-full">
          <CoverArt
            src={release.imageId !== null
              ? makeImageUrl(release.imageId, { size: 512 })
              : undefined}
          />
        </a>
        <a
          href="/releases/{release.id}"
          class="mt-1 block truncate font-medium hover:underline"
          title={release.title}
        >
          {release.title}
        </a>
        <div class="truncate text-sm text-gray-400">
          <CommaList items={release.artists} let:item>
            <a class="hover:underline" href="/artists/{item.id}">{item.name}</a>
          </CommaList>
        </div>
      </div>
    {/each}
  </FlowGrid>
{:else if $releasesQuery.error}
  <div>{$releasesQuery.error.message}</div>
{:else}
  <FullscreenLoader />
{/if}

// apps/mobile/src/app/(logged-in)/(library)/releases/index.tsx
import { Tabs } from 'expo-router'
import { makeImageUrl } from 'mutils'
import type { FC } from 'react'
import { SafeAreaView, View } from 'react-native'
import { FlatGrid } from 'react-native-super-grid'

import Button from '../../../../lib/atoms/Button'
import CoverArt from '../../../../lib/components/CoverArt'
import { trpc } from '../../../../lib/trpc'

const ReleasesPage: FC = () => {
  const releasesQuery = trpc.releases.getAllWithArtists.useQuery()

  const render = () => {
    if (releasesQuery.data) {
      return (
        <FlatGrid
          itemDimension={128}
          data={releasesQuery.data}
          renderItem={({ item: release }) => (
            <CoverArt
              src={
                release.imageId !== null ? makeImageUrl(release.imageId, { size: 512 }) : undefined
              }
            />
          )}
          keyExtractor={(release) => release.id.toString()}
        />
      )
    }

    return null
  }

  return (
    <View className="flex flex-1">
      <View className="flex-1">{render()}</View>
      <Button onPress={() => void releasesQuery.refetch()} title="Refetch" />
    </View>
  )
}

const Wrapper = () => (
  <SafeAreaView>
    <Tabs.Screen options={{ title: 'Releases', headerShown: false }} />

    <View className="flex h-full w-full bg-gray-800 p-4">
      <ReleasesPage />
    </View>
  </SafeAreaView>
)

export default Wrapper
