// apps/mobile/src/lib/atoms/Button.tsx
import type { FC } from 'react'
import { ActivityIndicator, Text, TouchableOpacity, View } from 'react-native'

import { cn } from '../classes'

const Button: FC<{
  kind?: 'solid' | 'outline' | 'text'
  onPress?: () => void
  loading?: boolean
  title?: string
  disabled?: boolean
}> = ({ kind = 'solid', onPress, loading, title, disabled }) => (
  <TouchableOpacity onPress={onPress} disabled={disabled}>
    <View
      className={cn(
        'flex flex-row items-center justify-center rounded border px-2 py-1',

        kind === 'solid' &&
          cn(
            'hover:bg-primary-600 border-transparent',
            disabled ? 'bg-gray-500' : 'bg-primary-500'
          ),
        kind === 'outline' &&
          cn('bg-transparent', disabled ? 'border-gray-500' : 'border-primary-500'),
        kind === 'text' && cn('border-transparent bg-transparent')
      )}
    >
      {loading && <ActivityIndicator size="small" color="black" className="mr-2" />}
      <Text
        className={cn(
          'text-sm font-medium',
          kind === 'solid' && cn(disabled ? 'text-gray-700' : 'text-black'),
          kind === 'outline' && cn(disabled ? 'text-gray-500' : 'text-primary-500'),
          kind === 'text' && cn(disabled ? 'text-gray-500' : 'text-primary-500')
        )}
      >
        {title}
      </Text>
    </View>
  </TouchableOpacity>
)

export default Button

// apps/client/src/lib/atoms/Button.svelte
<script lang="ts">
  import { slide } from '$lib/transitions/slide'
  import { cn, tw } from '$lib/utils/classes'

  import Loader from './Loader.svelte'

  export let disabled = false
  export let type: 'button' | 'submit' = 'button'
  export let kind: 'solid' | 'outline' | 'text' = 'solid'
  export let loading = false
  let class_: string | undefined = undefined
  export { class_ as class }

  export let layer: 700 | 800 = 800
</script>

<button
  on:click
  {disabled}
  {type}
  class={tw(
    'flex items-center rounded border px-2 py-1 text-sm font-medium transition',
    kind === 'solid' &&
      'bg-primary-500 hover:bg-primary-600 border-transparent text-black disabled:bg-gray-500 disabled:text-gray-700',
    kind === 'outline' &&
      cn(
        'border-primary-500 text-primary-500 bg-transparent disabled:border-gray-500 disabled:bg-transparent disabled:text-gray-500',
        layer === 700 && 'hover:bg-gray-600',
        layer === 800 && 'hover:bg-gray-700'
      ),
    kind === 'text' &&
      cn(
        'text-primary-500 border-transparent bg-transparent disabled:bg-transparent disabled:text-gray-500',
        layer === 700 && 'hover:bg-gray-600',
        layer === 800 && 'hover:bg-gray-700'
      ),
    class_
  )}
>
  {#if loading}
    <div transition:slide|local={{ axis: 'x' }}>
      <div class="relative mr-2 h-3.5 w-3.5">
        <Loader />
      </div>
    </div>
  {/if}
  <slot />
</button>
